apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset-websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset-websocket
  template:
    metadata:
      labels:
        app: superset-websocket
    spec:
      containers:
        - name: superset-websocket
          image: apache/superset:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_SSL
              value: "false"
          volumeMounts:
            - name: websocket-volumes
              mountPath: /home/superset-websocket
      volumes:
        - name: websocket-volumes
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: superset-websocket
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: superset-websocket
