apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
        - name: superset
          image: apache/superset:latest
          ports:
            - containerPort: 8088
          env:
            - name: SUPERSET_ENV
              value: production
            - name: SUPERSET_SECRET_KEY
              value: "bx4z2H%jrGo0"  
            - name: SUPERSET_DATABASE_URI
              value: "clickhousedb://superset_user:superset_password@clickhouse:9000/superset_db"
            - name: CLICKHOUSE_USER
              value: "superset_user"
            - name: CLICKHOUSE_PASSWORD
              value: "superset_password"
            - name: CLICKHOUSE_DB
              value: "superset_db"
            - name: CLICKHOUSE_PORT
              value: "9000"